---
driver: 
  name: vagrant
  cachier: true

provisioner:
  name: chef_zero
  chef_omnibus_install_options: -d /tmp/vagrant-cache/vagrant_omnibus

platforms:
  - name: ubuntu-14.04

suites:
- name: query
  run_list: [
    "recipe[apt]",
    "recipe[java]",
    "recipe[metrics-repose::query]",
    "recipe[metrics-repose::default]",
    "recipe[repose::filter-slf4j-http-logging]",
    "recipe[repose::filter-merge-header]",
    "recipe[repose::filter-cors]",
    "recipe[repose::filter-header-normalization]",
    "recipe[repose::filter-keystone-v2]",
    "recipe[repose::filter-add-header]",
    "recipe[repose::filter-ip-identity]",
    "recipe[repose::filter-rate-limiting]",
    "recipe[repose::filter-api-validator]"
  ]
  attributes:
    blueflood:
      query_servers: ["127.0.0.1", "127.0.0.2"]
      query:
        container_port: "9001"
    graphite_ip: "127.0.0.1"
    java:
      java_home: "/usr/lib/jvm/java-8-oracle-amd64"
      jdk_version: 8
      install_flavor: "oracle"
      accept_license_agreement: true
      oracle:
        accept_oracle_download_terms: true

- name: ingest
  run_list: [
    "recipe[apt]",
    "recipe[java]",
    "recipe[metrics-repose::ingest]",
    "recipe[metrics-repose::default]",
    "recipe[repose::filter-slf4j-http-logging]",
    "recipe[repose::filter-merge-header]",
    "recipe[repose::filter-cors]",
    "recipe[repose::filter-header-normalization]",
    "recipe[repose::filter-keystone-v2]",
    "recipe[repose::filter-add-header]",
    "recipe[repose::filter-ip-identity]",
    "recipe[repose::filter-rate-limiting]",
    "recipe[repose::filter-api-validator]"
  ]
  attributes:
    blueflood:
      ingest_servers: ["127.0.0.1", "127.0.0.2"]
      ingest:
        container_port: "9011"
    graphite_ip: "127.0.0.1"
    java:
      java_home: "/usr/lib/jvm/java-8-oracle-amd64"
      jdk_version: 8
      install_flavor: "oracle"
      accept_license_agreement: true
      oracle:
        accept_oracle_download_terms: true
