language: ruby
bundler_args: --without integration
cache: bundler
sudo: required
services: docker
rvm:
  - 2.2.4

env:
  matrix:
  - TESTS="unit"
  - TESTS="style"
  - TESTS="integration:docker[ingest-ubuntu-1404]"
  - TESTS="integration:docker[query-ubuntu-1404]"

before_install: curl -L https://www.getchef.com/chef/install.sh | sudo bash -s -- -P chefdk
install: chef exec bundle install --jobs=3 --retry=3 --without='vagrant'

# https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142455888
before_script: sudo iptables -L DOCKER || sudo iptables -N DOCKER

script: travis_retry chef exec bundle exec rake ${TESTS}

