name 'metrics-repose'
maintainer 'Rackspace Metrics'
maintainer_email 'sfo-devops@lists.rackspace.com'
license 'Apache 2.0'
description 'Installs/Configures metrics-repose'
long_description 'Installs/Configures repose and Rackspace Metrics configuration for repose'
version '0.1.2'

depends 'apt'
depends 'java'
depends 'repose'
